### ISSUE TITLE
My result

### ISSUE THREAD

**Issue by francko76** [bkerler/dump_avb_signature#2]
@Francko76 

Boot Signature Tool (c) B.Kerler 2017-2018
------------------------------------------------------
Kernel=0x00001000, length=0x00C2A000
Ramdisk=0x00C2B000, length=0x00893000
Second=0x014BE000, length=0x00000000
QCDT=0x014BE000, length=0x00000000
Signature start=0x014BE000
Traceback (most recent call last):
  File "verify_signature.py", line 171, in <module>
    main(sys.argv[1:])
  File "verify_signature.py", line 120, in main
    target,siglength,hash,pub_key,flag=dump_signature(signature)
TypeError: 'NoneType' object is not iterable

**Comment by youyim** [comment]
> @francko76
> 
> ## Boot Signature Tool (c) B.Kerler 2017-2018
> Kernel=0x00001000, length=0x00C2A000
> Ramdisk=0x00C2B000, length=0x00893000
> Second=0x014BE000, length=0x00000000
> QCDT=0x014BE000, length=0x00000000
> Signature start=0x014BE000
> Traceback (most recent call last):
> File "verify_signature.py", line 171, in 
> main(sys.argv[1:])
> File "verify_signature.py", line 120, in main
> target,siglength,hash,pub_key,flag=dump_signature(signature)
> TypeError: 'NoneType' object is not iterable
me too

**Comment by demonical** [comment]
both , try to decrypt AVB 2.0....

**Comment by bkerler** [comment]
Should be working with AVB 2.0 now. AVB vbmeta isn't supported right now, but not yet needed for boot image verification.
